# Generated by Django 3.0.3 on 2020-08-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('token', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.TextField(default='', max_length=100)),
                ('body', models.TextField(default='', max_length=400)),
                ('predicted', models.BooleanField(default=False)),
                ('prediction', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
