# Generated by Django 3.0.3 on 2020-06-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='text',
            new_name='body',
        ),
        migrations.AddField(
            model_name='tags',
            name='title',
            field=models.TextField(default='', max_length=100),
        ),
    ]
