# Generated by Django 3.0.3 on 2020-08-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='prediction',
            field=models.CharField(default='[]', max_length=100),
        ),
    ]
